routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('/request', 'RequestController@clear')->name('request.clear');

Route::resources([
	'items' => 'ItemController',
	'assets' => 'AssetController',
	'request' => 'RequestController',
	'tickets' => 'TicketController'
]);

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
	protected $fillable = ['name'];
	
    public function assets()
    {
        return $this->hasMany('App\Asset');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Asset;
use App\ProductStatus;
use Illuminate\Http\Request;
use Str;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Item::class);

        $items = Item::all();
        return view('items.index')->with('items', $items)
            ->with('assets', Asset::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Item::class);

        return view('items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Item::class);

        $validatedData = $request->validate([
            'name' => 'required|unique:items,name'
        ]);
        $item = new Item($validatedData);
        $item->save();
        return redirect(route('items.index'))
            ->with('message', "Item is added successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        $this->authorize('view', $item);

        $assets = Asset::all();
        $count = collect($assets)->where('item_id', $item->id)->where('product_status_id', 1)->count();
        $count_total = collect($assets)->where('item_id', $item->id)->count();
        return view('items.show')->with('item',$item)
            ->with('assets', $assets->where('item_id',$item->id))
            ->with('product_statuses', ProductStatus::all())
            ->with('count', $count)
            ->with('count_total', $count_total);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $this->authorize('update', $item);

        return view('items.edit')->with('item',$item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $this->authorize('update', $item);

        $item->name = $request->name;
        $item->save();
        return redirect(route('items.show', $item->id))
            ->with('message', "Item is updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $this->authorize('delete', $item);

        $assets = Asset::all();
        $count_total = collect($assets)->where('item_id',$item->id)->count();
        if($count_total === 0)
        {
            $item->delete();
            return redirect(route('items.index'))
                ->with('message', "Item has been deleted successfully.")
                ->with('alert','warning');
        }
        return back()
            ->with('message', 'Cannot delete Item with available asset.');
    }
}

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Edit Item
				</h1>
			</div>
		</div>

		{{-- edit div start --}}
		<div class="row">
			<div class="col-12 col-md-6 mx-auto">
				<form 
					action="{{route('items.update', $item->id)}}"
					method="post" 
				>
					@csrf
					@method('PUT')
					<label for="name">Category Name:</label>
					<input type="text" name="name" id="name" class="form-control form-control-sm" value="{{$item->name}}">
					<button class="btn btn-sm btn-warning mt-1">Edit</button>
				</form>
			</div>
		</div>
		{{-- edit div end --}}
	</div>
@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Items
				</h1>
			</div>
		</div>
		
		{{-- alert message --}}
		@includeWhen(Session::has('message'),'partials.alert')
		@if($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
					<li>{{$error}}</li>
					@endforeach
				</ul>
			</div>
		@endif
		{{-- end alert message --}}

		{{-- start item list --}}
		<div class="row">	
			{{-- sidebar start --}}
			<div class="col-4 col-lg-3">
				<div class="list-group sticky-top py-2" id="list-tab" role="tablist">
					<a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" >All Items</a>
					@can('isAdmin')
						<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" >Create Item</a>
					@endcan
				</div>
			</div>
			{{-- sidebar end --}}

			{{-- content page start --}}
			<div class="col-8 col-lg-9">
				<div class="tab-content row" id="nav-tabContent">
					<div class="tab-pane fade col-8 col-md-12 mx-auto active show" id="list-home" role="tabpanel">
							@foreach($items as $item)
								<?php $count = collect($assets)->where('item_id', $item->id)->where('product_status_id', 1)->count();
									$count_total = collect($assets)->where('item_id', $item->id)->count();
								 ?>
								@include('items.partials.card')
							@endforeach
					</div>

					{{-- start form --}}
					<div class="tab-pane fade col-8 col-md-12 mx-auto" id="list-profile" role="tabpanel">
						<form action="{{route('items.store')}}" method="post">
							@csrf
							<label for="name">Item Name:</label>
							<input type="text" name="name" id="name" class="form-control form-control-sm">
							<button class="btn btn-sm btn-primary mt-2">Create Item</button>
						</form>
					</div>
				</div>
			</div>
			{{-- content page end --}}
		</div>
		{{-- end item list --}}
	</div>
@endsection

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')
	<main class="py-4">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-4 col-lg-3 mx-auto">
					<h1>{{$item->name}}</h1>
					@include('items.partials.card-body',['view' => false])
					<hr>
					@can('isAdmin')
						<div class="my-5">
							<h5 class="text-center">Create Asset</h5>
							<form action="{{route('assets.store')}}" method="post" enctype="multipart/form-data">
								@csrf
								<?php $asset_code = strtoupper(Str::random(6))?>
									<label for="name">Asset Name:</label>
									<input type="text" name="name" id="name" class="form-control form-control @error('name') is-invalid @enderror">
									@error('name')
										<small class="d-block invalid-feedback">
											<strong>
												{{ $message }}
											</strong>
										</small>
									@enderror
									<small id="assetName" class="text-muted">Name of the product to be uploaded.</small>
									<label for="asset_code">Control Code:</label>
									
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text" id="basic-addon1">{{$item->id}}-</span>
										</div>
										<input 
											type="text" 
											id="asset_code" 
											name="asset_code" 
											aria-label="Asset Code" 
											aria-describedby="basic-addon1" 
											placeholder="Asset Code" 
											class="form-control" 
											value="{{$asset_code}}"
										>
									</div>

									<small id="controlCode" class="text-muted">Control Code should be unique to each unit.</small>
								<div class="form-group">
									<label for="item_id">Item Model</label>
									<select type="text" name="item_id" id="item_id" class="form-control" placeholder="Item Model" aria-describedby="ItemId" value="{{$item->id}}" disabled>
										<option value="{{$item->id}}" selected="">{{$item->name}}</option>
									</select>
									<small id="ItemId" class="text-muted">Model of the unit</small>
								</div>
								<input type="hidden" name="item_id" value="{{$item->id}}">
								<div class="form-group">
									<label for="image">Image:</label>
									<input type="file" name="image" id="image" class="form-control-file @error('image') is-invalid @enderror" aria-describedby="image" placeholder="Image">
									@error('image')
										<small class="d-block invalid-feedback">
											<strong>
												{{ $message }}
											</strong>
										</small>
									@enderror
									<small id="image" class="form-text text-muted">Item Sample Image</small>
								</div>
								<button type="submit" class="btn btn-primary w-100">Create Unit</button>
							</form>
						</div>
					@endcan
				</div>
				{{-- card list start --}}
				<div class="col-12 col-md-8 col-lg-9">
					<div class="row">
						@foreach($assets as $asset)
							<div class="col-12 col-sm-6 col-lg-4 my-3">	
								{{-- card start --}}
								<div class="card my-2">
									<img src="{{asset($asset->image)}}" alt="" class="card-img-top">
									<div class="card-body">
										<p class="card-text">
											<strong>{{$asset->name}}</strong>
										</p>
										<p class="card-text">
											Control Code: <strong>{{$asset->item_id}}-{{$asset->asset_code}}</strong>
										</p>
										<p class="cart-text">
											Status: <span class="badge badge-{{$asset->productStatus->id === 1 ? 'success' : 'danger'}}">{{$asset->productStatus->name}}</span>
										</p>

										{{-- Request Button --}}
										@include('assets.partials.request')
										
										@can('isAdmin')
											{{-- Edit Button --}}
											@include('assets.partials.edit')

											{{-- Delete Button --}}
											@include('assets.partials.delete')
										@endcan
									</div>
								</div>
							</div>
							{{-- card list end --}}
							@include('assets.partials.edit-modal')
						@endforeach
					</div>
				</div>
		</div>
	</main>
@endsection